### ISSUE TITLE
[Question] Proxy authentication

### ISSUE THREAD

**Issue by 0b9** [cubicbyte/reddit-account-generator#10]
How do I add the usernames and passwords for my proxies?

**Comment by cubicbyte** [comment]
Oh, I forgot that some proxies require authentication

This is not possible for now, but I will add this feature soon

**Comment by TEBandCo** [comment]
Would love this feature too! The TOR proxy has its… quirks.

**Comment by cubicbyte** [comment]
Done!

**Comment by TEBandCo** [comment]
> Done!

Amazing! Just found this project today and could see you were working on this already!
Great work :-)
