### ISSUE TITLE
High ban rate

### ISSUE THREAD

**Issue by TEBandCo** [cubicbyte/reddit-account-generator#13]
I'm currently experiencing a high ban rate (seemly 100%) on new accounts.

I'm testing to see if this is the script, proxy, or something I'm doing.

**First test**: Change from data centre proxies to residential proxies from [Webshare](https://www.webshare.io/?referral_code=8h2w3ln1w928). This seemed to make no change. 

**Next test**: Create accounts without specifying email address - currently created 10 accounts and will wait for a day or so to age them and test if they're banned or not.

**Comment by cubicbyte** [comment]
That's interesting

Just checked some of my accounts created during the whole testing time, I don't see any bans

I have only 2 assumptions: they didn't like your email or this ip was used by dirty people

Well, I'll be waiting for your results, keep me posted!

**Comment by TEBandCo** [comment]
Think this can be closed! I believe the email address I used originally (not the randomly generated ones) caused the subsequent accounts to be banned.
