### ISSUE TITLE
Fails captcha

### ISSUE THREAD

**Issue by Orangenal-name** [cubicbyte/reddit-account-generator#2]
![image](https://github.com/cubicbyte/reddit-account-generator/assets/44399774/038c9255-db97-476b-8050-2bc180d71522)

**Comment by cubicbyte** [comment]
This means that there are too many requests from the IP to solve the captcha, because you are not the only one using this proxy.

This means that you should just wait for the captcha cooldown to pass.

In the case of Tor, you will usually see <8 errors per account

**Comment by cubicbyte** [comment]
So it's a Tor problem, and can only be fixed by using other proxies.
