### ISSUE TITLE
Change browser fingerprinting after each account creation

### ISSUE THREAD

**Issue by ghost** [cubicbyte/reddit-account-generator#26]
I want to Change browser fingerprinting after each account creation.

This is to avoid Reddit detecting multiple accounts registered on the same browser.

According to my research, puppeteer can change  browser fingerprinting.

**Comment by cubicbyte** [comment]
First, I would advise you to learn what a browser fingerprint is.

In brief, it is formed from user agent, cookies, probably IP and other things. All of these things are changing after each account, so the fingerprint itself can't be created.
