### ISSUE TITLE
Issues running run_tor.py

### ISSUE THREAD

**Issue by Anonmike** [cubicbyte/reddit-account-generator#29]
![Screenshot_20240512-122614_Termux.jpg](https://github.com/cubicbyte/reddit-account-generator/assets/81964266/5b90a377-3ea2-45db-89ac-0d6c2bb856e7)

I get this error when I try running the script on termux (device is not rooted)

**Comment by cubicbyte** [comment]
Hi, it's probably because you forgot to change the permissions of file: `chmod +x libTor.so`

**Comment by Anonmike** [comment]
> Hi, it's probably because you forgot to change the permissions of file: `chmod +x libTor.so`

![Screenshot_20240512-215617_Termux.jpg](https://github.com/cubicbyte/reddit-account-generator/assets/81964266/27a066c9-1259-494c-8c8e-2be32ecf0463)

Can you pls give me the command for that? 
I tried using the files name still didn't work

**Comment by cubicbyte** [comment]
`chmod +x ~/reddit-account-generator/tor-expert-bundle-android-x86_64-13.0.14/tor/libTor.so`

or `chmod 777 ~/reddit-account-generator/tor-expert-bundle-android-x86_64-13.0.14/tor/libTor.so`

**Comment by Anonmike** [comment]
Thanks bro that fixed it 
Thanks a lot 🙏

**Comment by cubicbyte** [comment]
You're welcome!
