### ISSUE TITLE
[Question] Account Email

### ISSUE THREAD

**Issue by Wikinger8** [cubicbyte/reddit-account-generator#5]
Can you use one email for unlimited accounts?

**Comment by cubicbyte** [comment]
[Reddit's support](https://support.reddithelp.com/hc/en-us/articles/204535759-Is-it-ok-to-create-multiple-accounts-) says:

> Yes! You can create multiple accounts as long as you don't use them to vote for the same posts (this is considered vote manipulation and against the rules) or violate other rules outlined in [Reddit's Content Policy](https://www.redditinc.com/policies/content-policy)

So as long as you don't start breaking Reddit rules with these accounts, you'll be fine creating any number of accounts.
